/**
 * One-time cleanup after the Life Areas backend adopted the Astria UI Master
 * names (Health / Growth / Financial / Creativity / Spirituality) and the 0-100
 * scale in insight text.
 *
 * Insights saved before that still say "Body", "Mind"... and count points on the
 * old 0-10 scale. They are derived data (regenerated by the next check-in and
 * expiring within 30 days anyway), so this script simply removes them rather
 * than rewriting their text. Check-ins, scores and notes are NOT touched.
 *
 * Usage:
 *   node scripts/migrateLifeAreasInsights.js          # dry run, changes nothing
 *   node scripts/migrateLifeAreasInsights.js --apply  # delete the old insights
 */
require("dotenv").config();
const mongoose = require("mongoose");

const APPLY = process.argv.includes("--apply");

(async () => {
  await mongoose.connect(process.env.MONGODB_URL);
  const col = mongoose.connection.collection("lifegpsinsights");

  const total = await col.countDocuments({});
  console.log(`life GPS insights stored: ${total}`);

  if (!APPLY) {
    console.log("Dry run: nothing deleted. Re-run with --apply to delete them.");
    await mongoose.disconnect();
    return;
  }

  const res = await col.deleteMany({});
  console.log(`Deleted ${res.deletedCount} insights.`);
  await mongoose.disconnect();
})().catch((e) => {
  console.error("Migration failed:", e.message);
  process.exit(1);
});
